<template>
	<!-- To prevent the error:
	"The client-side rendered virtual DOM tree is not matching server-rendered content."
	that happens when we wrap the card in a nuxt-link,
	we perform routing when user clicks on the card programmatically.
	The <a> link will be generated by the button-primary > nuxt-link at SSR time,
	so we don't expect SEO issues.
	-->
	<div class="card" @click="$router.push(object.url)">
		<h2 class="card-title">{{ object.title }}</h2>
		<p v-if="object.subtitle" class="card-subtitle">
			{{ object.subtitle }}
		</p>
		<div
			:style="{
				backgroundImage: `url(${require('~/assets/images/' +
					object.img +
					'?webp')})`,
			}"
			:aria-label="object.alt"
			role="img"
			class="card-image"
		/>
		<p class="card-description">
			{{
				object.description.length > 60
					? object.description.slice(0, 60) + "..."
					: object.description
			}}
		</p>
		<!-- SEO: The link is contained inside the button -->
		<button-primary
			class="card-button"
			:title="object.buttonDesc"
			:link="object.url"
		/>
	</div>
</template>

<script>
import ButtonPrimary from "./ButtonPrimary.vue"
export default {
	name: "CardComponent",
	components: { ButtonPrimary },
	props: {
		object: {
			type: Object,
			required: true,
		},
	},
}
</script>

<style scoped>
.card {
	display: flex;
	flex-direction: column;
	padding: var(--space-1);
	border: 2px solid var(--color-neutral);
	border-radius: var(--border-radius);
	width: 100%;
	max-width: var(--card-max-width);

	color: var(--color-dark);
	cursor: pointer;
	background-color: var(--color-light-transparent);
}
.card:hover {
	border: 2px solid var(--color-dark);
}

.card-title {
	margin: 0;
}
.card-subtitle {
	font-style: italic;
	margin: var(--space-0) 0;
}

.card-image {
	display: block;
	margin: var(--space-1) 0;
	border-radius: var(--border-radius);
	background-color: var(--color-neutral);
	background-position: center;
	background-size: cover;
	aspect-ratio: 16 / 9;
	width: 100%;
	height: var(--image-height);
}

/* In flex items, margin-X auto basically pushes the element
 * as far as it can from the rest.
 * In this case it makes the button be at the very end of the
 * card (margin-top) as well as not taking full width (margin-right)
 */
.card-button {
	margin-top: auto;
	margin-right: auto;
}
</style>
